// lib/providers/language_provider.dart
// AUTO-GENERATED by auto_localize_flutter.py
// DO NOT EDIT MANUALLY - Run script again to regenerate

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:tcg_app/class/sharedPreference.dart';

/// Notifier für Sprach-Management
class LanguageNotifier extends StateNotifier<Locale> {
  final SaveData _saveData;

  LanguageNotifier(this._saveData) : super(const Locale('en')) {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final savedLang = await _saveData.loadWithKey('app_language');
    if (savedLang != null && (savedLang == 'en' || savedLang == 'de')) {
      state = Locale(savedLang);
    }
  }

  Future<void> setLanguage(Locale locale) async {
    state = locale;
    await _saveData.saveWithKey('app_language', locale.languageCode);
  }

  Future<void> toggleLanguage() async {
    final newLocale = state.languageCode == 'en' 
        ? const Locale('de') 
        : const Locale('en');
    await setLanguage(newLocale);
  }
}

/// Provider für Sprach-Notifier
final languageNotifierProvider = StateNotifierProvider<LanguageNotifier, Locale>((ref) {
  final saveData = SaveData();
  return LanguageNotifier(saveData);
});

/// Provider für Algolia Index basierend auf Sprache
final algoliaIndexProvider = Provider<String>((ref) {
  final locale = ref.watch(languageNotifierProvider);
  return locale.languageCode == 'de' ? 'cards_de' : 'cards';
});
