// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLepjhbVG6eik2yi2MIOYdb6OC_9vcI0',
    appId: '1:22327832859:web:a9c72aea54a1a07e1fa3be',
    messagingSenderId: '22327832859',
    projectId: 'tcg-app-e357e',
    authDomain: 'tcg-app-e357e.firebaseapp.com',
    storageBucket: 'tcg-app-e357e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZkQsRo1aA9z9QYGs_fuxUWupaRHtKE0',
    appId: '1:22327832859:android:f039a488d31707e81fa3be',
    messagingSenderId: '22327832859',
    projectId: 'tcg-app-e357e',
    storageBucket: 'tcg-app-e357e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfnlavHdEBBKaoS1PszuTRMMU6jHDqMVM',
    appId: '1:22327832859:ios:a2e225bc701f98331fa3be',
    messagingSenderId: '22327832859',
    projectId: 'tcg-app-e357e',
    storageBucket: 'tcg-app-e357e.firebasestorage.app',
    iosBundleId: 'com.example.tcgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfnlavHdEBBKaoS1PszuTRMMU6jHDqMVM',
    appId: '1:22327832859:ios:a2e225bc701f98331fa3be',
    messagingSenderId: '22327832859',
    projectId: 'tcg-app-e357e',
    storageBucket: 'tcg-app-e357e.firebasestorage.app',
    iosBundleId: 'com.example.tcgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQLepjhbVG6eik2yi2MIOYdb6OC_9vcI0',
    appId: '1:22327832859:web:bb6e2afd9937617d1fa3be',
    messagingSenderId: '22327832859',
    projectId: 'tcg-app-e357e',
    authDomain: 'tcg-app-e357e.firebaseapp.com',
    storageBucket: 'tcg-app-e357e.firebasestorage.app',
  );

}